services:
  postgres:
    image: postgres:17
    container_name: starlist-postgres
    environment:
      POSTGRES_DB: starlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - starlist-postgres-data:/var/lib/postgresql/data

volumes:
  starlist-postgres-data: