openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4.1-mini

app:
  images:
    base-url: ${S3_IMAGES_BASE_URL}


spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

