spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WBlndOjnO
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false # use logback SQL logger below instead (formats output better)
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

